version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
            
      - run:
          name: run commitlint
          command: | 
            git log --format=%B -n 1 $CIRCLE_SHA1 > $HOME/message.txt
            yarn commitlint -e $HOME/message.txt

      - run:
          name: run eslint
          command: yarn ci:eslint
          
      - run:
          name: run stylelint
          command: yarn ci:stylelint



